# H2 Veritabani Ayarlari
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/alstrackerdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=buse
spring.datasource.password=2934


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


